Refactored ci pipeline

diff --git a/.github/workflows/_unit_test_coverage.yml b/.github/workflows/_unit_test_coverage.yml
--- a/.github/workflows/_unit_test_coverage.yml
+++ b/.github/workflows/_unit_test_coverage.yml
@@ -28,7 +28,7 @@ jobs:
     runs-on: [self-hosted, GPU-h1z1-4Cards]
     outputs:
       diff_cov_file_url: ${{ steps.cov_upload.outputs.diff_cov_file_url }}
-      unittest_failed_url: ${{ steps.unittest_failed.outputs.unittest_failed_url }}
+      unittest_failed_url: ${{ steps.cov_upload.outputs.unittest_failed_url }}
     steps:
       - name: Code Prepare
         shell: bash
@@ -80,7 +80,7 @@ jobs:
             PARENT_DIR=$(dirname "$WORKSPACE")
             echo "PARENT_DIR:$PARENT_DIR"
             docker run --rm --net=host \
-            --cap-add=SYS_PTRACE --privileged --shm-size=64G \
+            --cap-add=SYS_PTRACE --shm-size=64G \
             -v $(pwd):/workspace -w /workspace \
             -v "${CACHE_DIR}/gitconfig:/etc/gitconfig:ro" \
             -v "${CACHE_DIR}/.cache:/root/.cache" \
@@ -108,6 +108,7 @@ jobs:
             echo "TEST_EXIT_CODE=${TEST_EXIT_CODE}" >> exit_code.env
             coverage combine coveragedata/
             coverage xml -o python_coverage_all.xml
+            sed -i.bak \"s#filename=\\\".*site-packages/fastdeploy#filename=\\\"fastdeploy#g\" python_coverage_all.xml
             COVERAGE_EXIT_CODE=0
             diff-cover python_coverage_all.xml --diff-file=diff.txt --fail-under=90 || COVERAGE_EXIT_CODE=9
             echo "COVERAGE_EXIT_CODE=${COVERAGE_EXIT_CODE}" >> exit_code.env
@@ -123,22 +124,41 @@ jobs:
           cd FastDeploy
           commit_id=${{ github.event.pull_request.head.sha }}
           pr_num=${{ github.event.pull_request.number }}
-          target_path=paddle-github-action/PR/FastDeploy/${pr_num}/${commit_id}/SM${compile_arch//,/_}/CoverageData
+          target_path=paddle-github-action/PR/FastDeploy/${pr_num}/${commit_id}/SM${compile_arch//,/_}
           wget  -q --no-proxy --no-check-certificate https://paddle-qa.bj.bcebos.com/CodeSync/develop/PaddlePaddle/PaddleTest/tools/bos_tools.py
           push_file=$(realpath bos_tools.py)
           python -m pip install bce-python-sdk==0.9.29
           diff_cov_file="diff_coverage.xml"
           if [ -f ${diff_cov_file} ];then
-            python ${push_file} ${diff_cov_file} ${target_path}
+            python ${push_file} ${diff_cov_file} ${target_path}/CoverageData
             target_path_stripped="${target_path#paddle-github-action/}"
-            DIFF_COV_FILE_URL=https://paddle-github-action.bj.bcebos.com/${target_path_stripped}/${diff_cov_file}
+            DIFF_COV_FILE_URL=https://paddle-github-action.bj.bcebos.com/${target_path_stripped}/CoverageData/${diff_cov_file}
             echo "diff_cov_file_url=${DIFF_COV_FILE_URL}" >> $GITHUB_OUTPUT
+            echo "diff_cov_file_url=${DIFF_COV_FILE_URL}" >> $GITHUB_ENV
           fi
+          unittest_result="test/failed_tests.log"
+          if [ -f ${unittest_result} ];then
+            python ${push_file} ${unittest_result} ${target_path}/UnitTestResult
+            target_path_stripped="${target_path#paddle-github-action/}"
+            UNIT_TEST_RESULT_URL=https://paddle-github-action.bj.bcebos.com/${target_path_stripped}/UnitTestResult/${unittest_result}
+            echo "unittest_failed_url=${UNIT_TEST_RESULT_URL}" >> $GITHUB_OUTPUT
+            echo "unittest_failed_url=${UNIT_TEST_RESULT_URL}" >> $GITHUB_ENV
+          fi
+
       - name: Determine Unit Succ and whether the coverage rate reaches 90%
         shell: bash
         run: |
           if [ "$TEST_EXIT_CODE" -eq 8 ]; then
+            if [ -z "${unittest_failed_url}" ]; then
+              echo "No diff unit failed file URL provided."
+            else
+              wget ${unittest_failed_url} || echo "Download unittest file failed, but continuing..."
+            fi
             echo "Unit tests failed (exit code 8)"
+            if [ -f failed_tests.log ];then
+              echo "Failed test cases:"
+              cat failed_tests.log
+            fi
             exit "$TEST_EXIT_CODE"
           fi
 
