[CI] Unified diff coverage upload logic

diff --git a/.github/workflows/_unit_test_coverage.yml b/.github/workflows/_unit_test_coverage.yml
--- a/.github/workflows/_unit_test_coverage.yml
+++ b/.github/workflows/_unit_test_coverage.yml
@@ -46,6 +46,7 @@ jobs:
     if: needs.check_cov_skip.outputs.can-skip != 'true'
     outputs:
       diff_cov_file_url: ${{ steps.cov_upload.outputs.diff_cov_file_url }}
+      all_cov_file_url: ${{ steps.cov_upload.outputs.all_cov_file_url }}
       unittest_failed_url: ${{ steps.cov_upload.outputs.unittest_failed_url }}
       diff_cov_result_json_url: ${{ steps.cov_upload.outputs.diff_cov_result_json_url }}
     steps:
@@ -266,6 +267,14 @@ jobs:
               echo "diff_cov_result_json_url=${DIFF_COV_JSON_URL}" >> $GITHUB_OUTPUT
               echo "diff_cov_result_json_url=${DIFF_COV_JSON_URL}" >> $GITHUB_ENV
             fi
+
+            all_coverage_file="python_coverage_all.xml"
+            if [ -f ${all_coverage_file} ]; then
+              python ${push_file} ${all_coverage_file} ${target_path}/CoverageData
+              ALL_COV_FILE_URL=https://paddle-github-action.bj.bcebos.com/${target_path_stripped}/CoverageData/${all_coverage_file}
+              echo "all_cov_file_url=${ALL_COV_FILE_URL}" >> $GITHUB_OUTPUT
+              echo "all_cov_file_url=${ALL_COV_FILE_URL}" >> $GITHUB_ENV
+            fi
           fi
 
           HAS_FAILED_TESTS=false
@@ -352,28 +361,60 @@ jobs:
     runs-on: ubuntu-latest
     timeout-minutes: 15
     env:
-      fd_archive_url: ${{ inputs.FASTDEPLOY_ARCHIVE_URL }}
+      diff_cov_file_url: ${{ needs.run_tests_with_coverage.outputs.diff_cov_file_url }}
+      all_cov_file_url: ${{ needs.run_tests_with_coverage.outputs.all_cov_file_url }}
     steps:
-      - name: coverage diff file download
-        shell: bash
-        env:
-          diff_cov_file_url: ${{ needs.run_tests_with_coverage.outputs.diff_cov_file_url }}
+      - name: Clone FastDeploy
+        uses: actions/checkout@v4
+        with:
+          fetch-depth: 0
+      - uses: actions/setup-python@v5
+        with:
+          python-version: '3.10'
+      - name: Fetch base branch
         run: |
-          wget -q --no-proxy ${fd_archive_url}
-          tar -xf FastDeploy.tar.gz
-          cd FastDeploy
+          echo "Fetching base branch: ${{ github.event.pull_request.base.ref }}"
+          git fetch origin ${{ github.event.pull_request.base.ref }}:refs/remotes/origin/${{ github.event.pull_request.base.ref }}
+
+      - name: Download diff coverage file
+        shell: bash
+        run: |
           if [ -z "${diff_cov_file_url}" ]; then
             echo "No diff coverage file URL provided."
             exit 0
           fi
-          wget "${diff_cov_file_url}" -O ./diff_coverage.xml || echo "Download cov file failed, but continuing..."
+
+          echo "Downloading diff coverage file..."
+          if ! wget --no-proxy "${diff_cov_file_url}" -O diff_coverage.xml; then
+            echo "Download failed, skipping upload."
+            exit 0
+          fi
+
+          echo "Downloading all coverage file..."
+          if ! wget --no-proxy "${all_cov_file_url}" -O python_coverage_all.xml; then
+            echo "Download failed, skipping upload."
+            exit 0
+          fi
+
+          if [ ! -s diff_coverage.xml ]; then
+            echo "Downloaded diff coverage file is empty!"
+            exit 0
+          fi
+
+          git diff origin/${{ github.event.pull_request.base.ref }}..HEAD --unified=0 > diff.txt
+          python -m pip install diff-cover
+
+          diff-cover python_coverage_all.xml --diff-file=diff.txt --json-report diff_coverage.json
+
+          sed -i 's|<source>/workspace/FastDeploy/fastdeploy</source>|<source>fastdeploy</source>|' diff_coverage.xml
+          sed -i 's|<source>/workspace/FastDeploy/fastdeploy</source>|<source>fastdeploy</source>|' python_coverage_all.xml
+
       - name: Upload diff coverage report
-        if: ${{ needs.run_tests_with_coverage.outputs.diff_cov_file_url != null && needs.run_tests_with_coverage.outputs.diff_cov_file_url != '' }}
-        uses: codecov/codecov-action@v5
+        if: always() && hashFiles('diff_coverage.xml') != ''
+        uses: codecov/codecov-action@v4
         with:
-          files: ./FastDeploy/diff_coverage.xml
-          name: python diff coverage
-          verbose: true
-          disable_search: true
-          commit_parent: false
+          files: ./diff_coverage.xml, ./python_coverage_all.xml
           flags: diff
+          name: python diff coverage
+          fail_ci_if_error: false
+          verbose: true
